### ISSUE TITLE
correção de swagger

### ISSUE THREAD

**Issue by vitorpcruz** [lgomesroc/ProductsApp#1]
correção de swagger:
- correção de ambiguidade de rotas entre get all products/get produts

**Comment by vitorpcruz** [comment]
`using Microsoft.AspNetCore.Mvc;
using ProductsApp.Models;

namespace ProductsApp.Controllers
{
    [ApiController]
    [Route("/api/[controller]")]
    public class ProductsController : ControllerBase
    {
        private readonly Product[] products = new Product[]
        {
            new() { Id = 1, Name = "Tomato Soup", Category = "Groceries", Price = 1},
            new() { Id = 2, Name = "Yo-yo", Category = "Toys", Price = 3.75M},
            new() { Id = 3, Name = "Hammer", Category = "Hardware", Price = 16.99M}
        };

        [HttpGet]
        public IActionResult GetAllProducts()
        {
            return Ok(products);
        }

        [HttpGet("{id:int}")]
        public IActionResult GetProduct(int id)
        {
            var product = products.FirstOrDefault((p) => p.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            return Ok(product);
        }
    }
}
`

**Comment by lgomesroc** [comment]
Opa valeu.
Vou pegar o seu repositório e testar.
Valeu.
